version: "3.8"
services:
   worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      CHANNELS: $CHANNELS
      ADMINS: $ADMINS
      LOG_CHANNEL: $LOG_CHANNEL
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_URI: $DATABASE_URI
      PICS: $PICS
      AUTH_CHANNEL: $AUTH_CHANNEL
      AUTH_USERS: $AUTH_USERS
      COLLECTION_NAME: $COLLECTION_NAME
      CUSTOM_FILE_CAPTION: $CUSTOM_FILE_CAPTION
      HEROKU_API_KEY: $HEROKU_API_KEY
      P_TTI_SHOW_OFF: $P_TTI_SHOW_OFF
      PUBLIC_FILE_STORE: $PUBLIC_FILE_STORE
      SINGLE_BUTTON: $SINGLE_BUTTON
      SPELL_CHECK_REPLY: $SPELL_CHECK_REPLY
      SUPPORT_CHAT: $SUPPORT_CHAT
      UPSTREAM_REPO: $UPSTREAM_REPO
